server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: inventory-management-service
  
  # Datastore settings
  data:
    mongodb:
      host: localhost
      port: 27017
      database: skishop_inventory
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0
  
  # PostgreSQL settings
  datasource:
    url: jdbc:postgresql://localhost:5432/skishop_inventory
    username: ${DB_USERNAME:skishop_user}
    password: ${DB_PASSWORD:skishop_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 10

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Tokyo
    open-in-view: false

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Kafka settings
  # Redis settings
  # (Redis settings are integrated above in data section)
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0

  # Security settings
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/skishop

# Logging settings
logging:
  level:
    com.skishop.inventory: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.kafka: INFO
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/inventory-management-service.log

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
# Application settings
app:
  inventory:
    low-stock-threshold: 5
    cache:
      ttl: 300  # 5 minutes
    image:
      max-size: 10MB
      allowed-types: jpg,jpeg,png,webp
  
  azure:
    storage:
      account-name: ${AZURE_STORAGE_ACCOUNT_NAME:}
      account-key: ${AZURE_STORAGE_ACCOUNT_KEY:}
      container-name: product-images

# OpenAPI settings
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Inventory Management Service API
    description: REST API for Inventory Management Service
    version: 1.0.0
    contact:
      name: Ski Shop Team
      email: support@skishop.com
